// Generated by https://quicktype.io

export interface PostResponse {
  data:  Post[];
  total: number;
  page:  number;
  limit: number;
}

export interface Post {
  id:          string;
  image:       string;
  likes:       number;
  tags:        string[];
  text:        string;
  publishDate: string;
  owner:       Owner;
}

export interface Owner {
  id:        string;
  title:     Title;
  firstName: string;
  lastName:  string;
  picture:   string;
}

export enum Title {
  MS = "ms",
  Miss = "miss",
  Mr = "mr",
  Mrs = "mrs",
}
